CREATE SEQUENCE tracking_serial_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE envio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tracking_serial BIGINT NOT NULL UNIQUE,
  codigo_seguimiento VARCHAR(20) NOT NULL UNIQUE,
  remitente_nombre VARCHAR(120) NOT NULL,
  remitente_telefono VARCHAR(30) NOT NULL,
  remitente_correo VARCHAR(254) NOT NULL,
  destinatario_nombre VARCHAR(120) NOT NULL,
  destinatario_telefono VARCHAR(30) NOT NULL,
  destinatario_correo VARCHAR(254) NOT NULL,
  destino_calle VARCHAR(180) NOT NULL,
  destino_numero VARCHAR(30) NOT NULL,
  destino_ciudad VARCHAR(120) NOT NULL,
  peso_kg NUMERIC(10,3) NOT NULL CHECK (peso_kg > 0),
  tipo_servicio VARCHAR(20) NOT NULL CHECK (tipo_servicio IN ('ESTANDAR','EXPRES','PROGRAMADO')),
  fecha_entrega_programada DATE,
  fecha_entrega_estimada DATE NOT NULL,
  costo_estimado_cop NUMERIC(12,2) NOT NULL CHECK (costo_estimado_cop >= 0),
  estado VARCHAR(40) NOT NULL CHECK (estado IN ('PENDIENTE_RECOGIDA','CANCELADO')),
  creado_en TIMESTAMP WITH TIME ZONE NOT NULL,
  actualizado_en TIMESTAMP WITH TIME ZONE NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT programado_requiere_fecha CHECK ((tipo_servicio = 'PROGRAMADO') = (fecha_entrega_programada IS NOT NULL)),
  CONSTRAINT tracking_serial_rango CHECK (tracking_serial BETWEEN 1 AND 99999999)
);

CREATE INDEX ix_envio_creado ON envio(creado_en DESC, id DESC);
CREATE INDEX ix_envio_estado ON envio(estado);

CREATE TABLE evento_envio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  envio_id BIGINT NOT NULL REFERENCES envio(id),
  tipo VARCHAR(30) NOT NULL CHECK (tipo IN ('REGISTRO','CANCELACION')),
  estado_resultante VARCHAR(40) NOT NULL,
  publico BOOLEAN NOT NULL,
  ocurrido_en TIMESTAMP WITH TIME ZONE NOT NULL,
  descripcion VARCHAR(500) NOT NULL
);
CREATE INDEX ix_evento_envio_fecha ON evento_envio(envio_id, ocurrido_en DESC, id DESC);

CREATE TABLE auditoria_envio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  envio_id BIGINT NOT NULL REFERENCES envio(id),
  accion VARCHAR(30) NOT NULL CHECK (accion IN ('EDICION','CANCELACION')),
  actor VARCHAR(100) NOT NULL,
  ocurrido_en TIMESTAMP WITH TIME ZONE NOT NULL,
  detalle TEXT NOT NULL
);
CREATE INDEX ix_auditoria_envio_fecha ON auditoria_envio(envio_id, ocurrido_en DESC, id DESC);
